version: '3'

services:
    fullnode1:
        container_name: 'fullnode1'
        image: blockchain_fullnode:latest
        volumes:
          - ./fullnode:/LW-BC-IDMS
          - ./conf/conf1:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.2
    fullnode2:
        container_name: 'fullnode2'
        image: blockchain_fullnode:latest
        volumes:
          - ./fullnode:/LW-BC-IDMS
          - ./conf/conf2:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.3
    fullnode3:
        container_name: 'fullnode3'
        image: blockchain_fullnode:latest
        volumes:
          - ./fullnode:/LW-BC-IDMS
          - ./conf/conf3:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.4
    fullnode4:
        container_name: 'fullnode4'
        image: blockchain_fullnode:latest
        volumes:
          - ./fullnode:/LW-BC-IDMS
          - ./conf/conf4:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.5
    fullnode5:
        container_name: 'fullnode5'
        image: blockchain_fullnode:latest
        volumes:
          - ./fullnode:/LW-BC-IDMS
          - ./conf/conf5:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.6

    lightweightnode1:
        container_name: 'lightweightnode1'
        image: blockchain_fullnode:latest
        volumes:
          - ./lightweightnode:/LW-BC-IDMS
          - ./conf/lwconf1:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.224
    lightweightnode2:
        container_name: 'lightweightnode2'
        image: blockchain_fullnode:latest
        volumes:
          - ./lightweightnode:/LW-BC-IDMS
          - ./conf/lwconf2:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.225
    lightweightnode3:
        container_name: 'lightweightnode3'
        image: blockchain_fullnode:latest
        volumes:
          - ./lightweightnode:/LW-BC-IDMS
          - ./conf/lwconf3:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.226
    lightweightnode4:
        container_name: 'lightweightnode4'
        image: blockchain_fullnode:latest
        volumes:
          - ./lightweightnode:/LW-BC-IDMS
          - ./conf/lwconf4:/LW-BC-IDMS/conf
        tty: true
        networks:
          net-172.28.0.0:
            ipv4_address: 172.28.0.227

networks:
    net-172.28.0.0:
        name: net-172.28.0.0
        ipam:
            config:
                - subnet: 172.28.0.0/24
